### ISSUE TITLE
GöeIP-0002: Set Validator-Balances to Ninety-two Quintillion Ether

### ISSUE THREAD

**Issue by q9f** [eth-clients/goerli#101]
```
göeip: 0002
title: Set Validator-Balances to Ninety-two Quintillion Ether
description: Increase the total supply to prevent the network from gaining significant value.
author: Martin Holst Swende (@holiman), Afri Schoedon (@q9f)
discussions-to: https://github.com/goerli/testnet/issues/101
status: Draft
type: Standards Track
category: Core
created: 2022-04-01
```

## Abstract
Set the balance of active Clique validators to ninety-two quintillion Ether.

## Motivation
Setting the total supply to an enormously high value will prevent anyone from ever expecting a Clique-based, Ethereum developer-focused testnet to have any non-zero value.

## Specification
The keywords “MUST,” “MUST NOT,” “REQUIRED,” “SHALL,” “SHALL NOT,” “SHOULD,” “SHOULD NOT,” “RECOMMENDED,” “MAY,” and “OPTIONAL” in this document are to be interpreted as described in RFC 2119.

As per `FORK_BLOCKNUM` on the specified Clique-proof-of-authority network, the balance of all active signers shall be set to `92000000000000000000000000000000000000` (ninety-two quintillion Ether, `0x45368e347c3e8bcc6f2d29c000000000`).

Where `FORK_BLOCKNUM` is defined for the following networks:
* Goerli Testnet: `TBD`

Any previous balance must be ignored and shall be overridden. No other irregular state changes are intended.

## Rationale
As opposed to GöeIP-0001, this proposal does not require hard-coding a specific key forever. Instead, it allows being more generally applied to any Clique-based proof-of-authority network.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by shemnon** [comment]
Generally speaking, I think asking clients to implement an irregular state change is a slippery slope, even for a test network.  Second, special handling of a test network has historically been problematic, look at morden.

Hence I am -1 to this proposal all all like it.

**Comment by q9f** [comment]
@shemnon Thank you for your comment, Danno!

The rough consensus at the last ACD-135 was not to apply any special treatment for Goerli and instead consider a regenesis sometime after the merge.

**Comment by ayanamidev** [comment]
@q9f Sounds bullish for gETH unfortunately, those crazy speculatoors 😂

**Comment by noam-alchemy** [comment]
Hey - can we revive this discussion? With the new testnet strategy and the sunsetting of Kovan/Ropsten/Rinkeby, the most common feedback we hear from developers is concern around the scarcity of gEth. I think this would go a long way to making sure this is a viable long term testnet that allows for mainnet-like application development and concentrated liquidity/composability. 

I would love to understand the tradeoffs/risks here a little better too. Possible to re-open this issue for now?

cc @q9f @shemnon

**Comment by noam-alchemy** [comment]
Sounds good thanks @q9f! Possible to re-open for tracking purposes?

**Comment by q9f** [comment]
Yes, we would have to write a new proposal though, after merge.

**Comment by dpulife** [comment]
Hi there, please give me 32 ETH, thank you!
0x194Bef0264F65946F60AEbdC6aaA9b47e68E82De

**Comment by q9f** [comment]
closing in favor of #129
