### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by toglokkoplak** [eth-clients/goerli#113]
please give me 32 ETH , I want to start being a validator in goerli

0x9b7437FD97B1EaE0457c3e77b6d3DC03717056C4

**Comment by xx6412223** [comment]
0x91045Cd1BCabD0d9B47456ba53FA03EDdC3C373b
Hi there, I also need 32+ (some more for gas fee ?) Goerli ETH to became a validator 
Thanks

**Comment by zed-wong** [comment]
0x1AE60D36412a6745fce4d4935FF5Bf2b8139a371
Hi there, please give me 32 ETH, thank you!

**Comment by dpulife** [comment]
Hi there, please give me 32 ETH, thank you!
0x194Bef0264F65946F60AEbdC6aaA9b47e68E82De

**Comment by josesistemas31** [comment]
I need 32 ETH, please. 
0x80B89aC7a50074DFa570AF4DBb4a3d5592C28E5C
