### ISSUE TITLE
32 Goerli Eth

### ISSUE THREAD

**Issue by abhudia04** [eth-clients/goerli#119]
Hello, I am currently working on a project and I would like to do some testing on ethereum testnet. I was hoping to run a validator and require 32 ETH. I wonder if you would be able to help please? 

Wallet address: v0x37aCDe9533c993b8a3F7da55c8D17e9391045474

Many thanks in advance.
Alpesh

**Comment by james-chien** [comment]
0xa86531b48A8B42dAAE3A6bB86C68Ac0E057F3601
32 ETH with 1 validator
Thanks
