### ISSUE TITLE
[Comms] Goerli Testnet Community Call #6

### ISSUE THREAD

**Issue by q9f** [eth-clients/goerli#129]
### Goerli Testnet Community Call #6

Date / Time
- Tuesday, November 1st, 2022, [3 pm UTC](https://savvytime.com/converter/utc-to-germany-berlin-canada-toronto-ca-san-francisco-china-shanghai-india-mumbai/nov-1-2022/3pm)
- Jitsi: _snip_
- Discussion: <https://ethereum-magicians.org/t/testnet-workgroup-paths-out-of-the-goerli-supply-mess/11453>

Agenda
- Post-merge testnet situation: Ropsten, Goerli, Sepolia
  - context: <https://ethereum-magicians.org/t/og-council-post-merge-testnets/9034>
  - context: <https://www.youtube.com/watch?v=1UtcvVve32A>
- Goerli testnet supply issue
  - issue: Goerli OTC trading
  - issue: faucet hacking/draining
  - issue: huge GoETH demand to test staking setup
  - consequence: stopped handing out goerli ether
- Potential paths going forward
  - custom testnet protocol
    - #97 
    - #101 
    - withdrawals? `WITHDRAWAL_BOOST_FACTOR` idea by @parithosh 
  - new ephemeral testnet
    - Holešovice idea
    - reset every X months on a given date
    - needs commitment by client teams and infrastructure providers
    - testnet for stakers by @taxmeifyoucan 
      - https://notes.ethereum.org/@mario-havel/stakers-testnet
 - preserve state in a regenesis event
   - precedence? feasibility?

All developers, contributors, and volunteers are invited.

**Comment by ligi** [comment]
ICS for convenient calendar adding (less convenient as a ZIP as github does not allow ICS directly here)

[goerli-testnet-community-call-6.zip](https://github.com/eth-clients/goerli/files/9860863/goerli-testnet-community-call-6.zip)

**Comment by edidoo** [comment]
Would be very glad to join in and share some insights and possible ideas on the way forward to ease this crunch. I have been greatly impacted with more headaches on getting ample quantities of GoETH for my team to execute tests. Hopefully there is a good solution to this ASAP along with a couple of issues reported pertaining to the goerli network.

**Comment by Prankyzz** [comment]
hi @q9f you said that for now sepolia can replace like goerli for validators and others so please send 1000 sepolia for that sir so i don't have to look for goerli for now
0x9BDe91219DAb4a30B7151a5cc03cdeDb404804Ca
thank you appreciate!

**Comment by taxmeifyoucan** [comment]
I probably won't be able to make the call as it overlaps with [EPF](https://github.com/eth-protocol-fellows/cohort-three/issues/41).
I'd like to share my insight on options of an emphemeral testnet for stakers - https://notes.ethereum.org/@mario-havel/stakers-testnet. It is not silver bullet solution but might help a lot in the long term

**Comment by q9f** [comment]
New link

[zoo ](https://chainsafe-io.zoom.us/j/81891522989?pwd=V1IxSEJrdHdrYks1TEozb0NjdVBHUT09)

**Comment by q9f** [comment]
Sorry 

https://chainsafe-io.zoom.us/j/89813607840?pwd=TjFDZHBreElwdWZhVjYvYjg3RHEzUT09

**Comment by q9f** [comment]
thanks, everyone for attending and chiming in and sorry for the jitsi issues.

### rough meeting minutes (nov/01/2022)

##### problem statement
- huge demand for goerli ether due to testing staker setups (32 ether for each validator)
- after testnet deprecation earlier this year, a lot of projects migrate to goerli instead of sepolia
- faucets getting drained or hacked rendering the network unusable for many developers
- goerli ether being traded otc does make it easier to buy them even though they are free
- current situation breaks down into two problems
  - stakers have no easy way to test staking
  - developers actually pay money to test their applications

##### discussion of protocol changes
- custom protocols for testnets have been an issue in the past (see: morden consensus failure)
- execution-layer teams are not willing to support a testnet-only fork or custom protocol
- there might be a chance to utilize upcoming withdrawals in capella fork on the consensus-layer side
  - add a constant that introduces a withdrawal boost factor that is "1" on all networks
  - but can be tweaked for testing or testnet environments (here: goerli)
  - benefit: trivial to implement (one constant, one multiplier)
    - https://github.com/ethereum/consensus-specs/pull/3073
  - potential drawbacks: people abusing the queues to deposit and exit the validator set to farm more goerli
  - at least this would reduce pressure on faucets
  - another caveat: make sure to not hit the max integer value on any account any time soon
  - **action item:** simulate deposits/withdrawals and come up with a good number for goerli to extend life for at least 2 years
    - https://github.com/eth-clients/goerli/issues/135

##### application-layer point of view
- need long-term guarantees for testnets
- the migration from kovan/rinkeby to goerli was very short notice for many projects
- migration for larger projects is often very involved
- maintaining support for more than one testnet binds a lot of resources
- currently huge demand on goerli, the base fee is around 30 gwei (similar levels to mainnet)
- inflating the supply might also increase the base fee

##### proposal to have a "release and support schedule" for testnets
- launch new testnet every 2 or 3 years, pre-announce and "end-of-life date" (5 years lifetime? tbd)
  - goerli end of life: 2024?
  - sepolia end of life: 2026?
  - sepolia would be the right place to migrate/test applications
  - sepolia is permissionless, has better stability guarantees, and better total supply
- 5-years testnet long-term support seems reasonable but for goerli this is still too short notice
  - many projects are migrating to goerli instead of sepolia as we speak
  - missed opportunity prior to the merge to communicate clearly the expectations for the testnets
- benefits: gives projects long-term guarantees for operation and planning capabilities for future migrations
- _open question_: is there a benefit for applications to run on permissionless networks (concerns about the permissioned nature of sepolia)?
- _open question_: if goerli is deprecated, where to test large validator sets for consensus-layer teams?
  - in general, need to discuss the different needs of application and protocol developers
  - there is always a need for a ropsten-like testnet
- **action item**: work out and present a testnet release and support schedule; discuss with community stakeholders
  - https://github.com/eth-clients/goerli/issues/136

##### ephemeral testnet for stakers
- mario worked out a proposal
  - https://notes.ethereum.org/@mario-havel/stakers-testnet
- **action item**: refine this with the home-staker community and map out a launch and maintenance plan

please correct me if I got something wrong or forgot an aspect

**Comment by chrishobcroft** [comment]
On a related note: https://github.com/ethereum/ethereum-org-website/pull/8481

**Comment by shaghil65** [comment]
Kindly send me 320 goerli eth for testing the transaction as I am unable to get free ether.
0x47574F2a8e75cd7942763F1caFF9FAf2473fcC0c
