### ISSUE TITLE
Goerli Eth needed

### ISSUE THREAD

**Issue by togglebytes** [eth-clients/goerli#130]
320 Goerli Eth with 3 Validators please
0x3a42e2288a7531A978a1b746f65aabF43d0C5743

**Comment by Anonimscrypt** [comment]
Hi everyone if you have trouble finding goerli testnet And need some tesnet goerli eth you can contact me to buy
Telegram: 
https://t.me/SnowdenResearch
Im selling GoerliETH
📌Price:
20 Goerli ETH for $5
40 Goerli ETH for $10
50 Goerli ETH for $12
💳Proof of Supply:
https://goerli.etherscan.io/address/0x0b4a7e3e7DBa45509F1948eD388d521f862270B1
