### ISSUE TITLE
Request for GöETH for ETHBrno² hackathon

### ISSUE THREAD

**Issue by burningtree** [eth-clients/goerli#133]
ETHBrno² is a hackathon focused on Privacy & Security that will take place 11 - 13 November 2022. More information: http://ethbrno.cz/

We would like to offer hackers the opportunity to obtain testnet tokens. We are preparing a simple faucet where they will be able to connect to their wallet and use an offchain signature to request some.

Verification that they are ETHBrno² hackers is done by checking if they own an ETHBrno² SBT (which we do in collaboration with FactoryDAO). The only way to mint this SBT will be through a one-time physical QR code that we will give them on the spot.

This guarantees that:
- only people who are our participants can request tokens
- we will only distribute tokens and amount that people directly request (in our faucet)

Each hacker (address) will have a quota of tokens that he can get a total of `amount_max_per_user`. A single request will give him `amount_per_request` tokens - request can be repeated in `request_cooldown` time.

Suggested values:
- `amount_max_per_user` = 200 ETH
- `amount_per_request` = 50 ETH
- `request_cooldown` = 5 hour

We expect a maximum of 250 hackers at the hackathon, so we are asking for a total of (`200*250`):
- **50 000 GöETH**

The assumption is that not everything will be released, realistically it could be 5-10k. The remaining tokens can be returned or used for the next hackathon.

Recipient: `0x6D639104757Cd7A3e4B649d9f8BeA6B204F49Cd6` (ethbrno.eth)

**Comment by q9f** [comment]
Not giving out Goerli until we resolve the supply issue. Could you live on Sepolia for now?

**Comment by burningtree** [comment]
> Not giving out Goerli until we resolve the supply issue. Could you live on Sepolia for now?

We discussed this with a few hackers and came to the conclusion that Sepolia is fine, but Goerli is really needed.

The main reason is the ecosystem, which is almost non-existent on Sepolia. The minimum projects on which Eth composability is based have deployment there, which is a big obstacle. For example, it's projects like:
- Chainlink - this is biggest problem
- Tenderly
- Alchemy
- Uniswap
- MakerDAO
- Synthetix
...

In Berlin you make such a great testnet that you can't be without it :)

The hackathon starts on November 11, we don't need them right now. If we get a lot less GoerliETH tokens, it's better than nothing. I think we can be satisfied with 25k/10k as well.

BTW, can I ask for some source where I can read more about the supply problem?

**Comment by q9f** [comment]
Sent!

**Comment by q9f** [comment]
> BTW, can I ask for some source where I can read more about the supply problem?

Sure, https://ethereum-magicians.org/t/testnet-workgroup-paths-out-of-the-goerli-supply-mess/11453
