### ISSUE TITLE
simulate deposits/withdrawals under constraints of prater with various withdrawal boost factor

### ISSUE THREAD

**Issue by q9f** [eth-clients/goerli#135]
* https://github.com/eth-clients/goerli/issues/129
* https://github.com/ethereum/consensus-specs/pull/3073

**Comment by pk910** [comment]
Hmm, if I got the proposal right this withdrawal boost factor applies to partial withdrawals, too? (withdraw_balance gets called from process_full_withdrawals & process_partial_withdrawals)
So a farmer could simply run a validator, deposit large amounts of funds and wait for it to be returned via the next partial withdrawal.

This could be problematic in combination with the caveat you've mentioned on the ethereum-magicians discussion thread: 
``make sure to not hit the max integer value on any account any time soon``

Even with a low factor of only 2 a farmer could potentially double his balance every 1-2weeks (partial withdrawal interval).
The limit will be reached quickly this way.

**Comment by q9f** [comment]
the general notion today was that also CL teams do not deem testnets important enough for such an effort.

we should start preparing application developers for sepolia and holesovice.
