### ISSUE TITLE
request geth 

### ISSUE THREAD

**Issue by rocqina** [eth-clients/goerli#139]
0xe3FAe7669a1789532c2aC19384239F78bB6535e6
64Eth with 2 validators
Thanks

**Comment by Anonimscrypt** [comment]
Hello everyone, if you have trouble finding goerli testnet you can contact me to buy Telegram: https://t.me/SnowdenResearch Im Selling $Goerli $ETH ! 💰20 Goerli ETH = $5 💰50 Goerli ETH = $12 💳addres Of supply: 0x0b4a7e3e7DBa45509F1948eD388d521f862270B1
