### ISSUE TITLE
Need some sepolia

### ISSUE THREAD

**Issue by Quinshant** [eth-clients/goerli#140]
hi Afri @q9f help me to get 300 sepolia really need it because goerli is very hard to get thanks for helping me!
0xDeFA440B98f7B0D98975825702256bB9EeA07121

**Comment by q9f** [comment]
Sure!

**Comment by dumpslabs** [comment]
@q9f can you give it to me too, I need it to share with active users who are working on a development project?
i need about 1000-2000 sepolia if possible
0x97dD586a646cbb0f6075B074c3767Ce9d5455285
