### ISSUE TITLE
sepolia for community active

### ISSUE THREAD

**Issue by dumpslabs** [eth-clients/goerli#141]
hello can anyone help to get some sepolia to distribute to active users for development projects
the faucet is not giving us enough eth at the moment we need 2000 Test tokens i hope i can get it from here
thanks!
0x97dD586a646cbb0f6075B074c3767Ce9d5455285

**Comment by qjawe** [comment]
https://faucetlink.to/sepolia is the best bet for now...

as nobody will send a large volume of sepolia ETH

**Comment by dumpslabs** [comment]
> https://faucetlink.to/sepolia is the best bet for now...
> 
> as nobody will send a large volume of sepolia ETH

I only need 1000 for now if there is any please sir I need it 🙂

**Comment by qjawe** [comment]
@dumpslabs please read the ethereum community call https://github.com/eth-clients/goerli/issues/129

**Comment by qjawe** [comment]
if there is large volume faucet let me know

**Comment by dumpslabs** [comment]
> jika ada faucet volume besar beri tahu saya

usually Afri @q9f  helps people who need large amounts of funds but it seems he is busy at the moment

**Comment by q9f** [comment]
Sent, but please consider using the faucets above.

**Comment by dumpslabs** [comment]
thanks Afri you are a lifesaver, we will use it wisely!

**Comment by qjawe** [comment]
can anyone help to get some sepolia to distribute to active users for development projects
the faucet is not giving us enough eth at the moment we need 2000 sepolia faucet i hope i can get it from here
thanks!

0x7B88DF8AF7a283e3dc84A7Fd97Fde19cAbb90eD4

https://sepolia.etherscan.io/address/0x7b88df8af7a283e3dc84a7fd97fde19cabb90ed4

**Comment by qjawe** [comment]
I am testing on https://twitter.com/official_1combo project

**Comment by dumpslabs** [comment]
don't send him, he has other intentions he followed my words to ask for sepolia his goal is different lol
