### ISSUE TITLE
Need some Goerli ETH for USDT

### ISSUE THREAD

**Issue by ofumbi** [eth-clients/goerli#142]
Im trying to setup some validators but need some Goerli ETH like 65 ETH, can anyone send me. will send you back 15  USDT for your troubles, thanks
 0xaaF5e5b59f765f5a7e4421e8e0C9fA026d3AB9ac

**Comment by ofumbi** [comment]
which faucet?  Your comment is not helping  Im paying @q9f why you close me? I still not have any goerli.

**Comment by q9f** [comment]
Goerli is not for sale

**Comment by dumpslabs** [comment]
> which faucet? Your comment is not helping Im paying @q9f why you close me? I still not have any goerli.

give me a twitter username i'll give it some there
