### ISSUE TITLE
can someone gimme 100 goerli in exchange for 2 nfts worth US$20 each?

### ISSUE THREAD

**Issue by ultperf** [eth-clients/goerli#144]
to this address : 0xF47DdD15d21dD39E2fFBA671913573a0eD7A1cC4

need 1000 only. first 10 gets the nft from vipsland.com

will send the nft to your address

Thx!

this msg is valid til 20th Jan 2023

**Comment by q9f** [comment]
Goerli is free, you don't need any NFTs.

**Comment by ultperf** [comment]
can you please give me 200 more? i will gift yout back 3 nfts i've created when the nfts are ready. doing last test phase now.
thx in advance. 

p.s. : how did u get so many by the way?

**Comment by q9f** [comment]
> @q9f can you please give me 200 more? i will gift yout back 3 nfts i've created when the nfts are ready. doing last test phase now.

I don't want any NFTs, sorry.

> p.s. : how did u get so many by the way?

I [allocated 90 million to my wallet](https://github.com/eth-clients/goerli/blob/eda0f63d0f5b2249b0f155e1d74f8cb10294cd17/goerli/geth/goerli.genesis#L306-L308) when I [launched the network](https://www.youtube.com/watch?v=d961TWOSnBU).

**Comment by ultperf** [comment]
@q9f how can i get 900 more from you? since u have so much.

i have a 250k unique visitor to my blog. if u need publicity over some launches, i can provide 1 mth backlink 250 character ad + permanent backlink of DA 75+ to your website or link in exchange. 

appreciate this help in return.

currently getting goerli from https://goerlifaucet.com/

p.s. : my goerli was hacked from github repo a few weeks ago and stolen after i saved them over many months. 
now i'm just reduced to begging for 900 more. 

do mention how i can repay this to you in future and see if you require anything in future. thx.

**Comment by Anonimscrypt** [comment]
Hello, if you have trouble finding goerli testnet you can contact me to buy Telegram: https://t.me/SnowdenResearch Im Selling $Goerli $ETH ! 💰20 Goerli ETH = $5 💰50 Goerli ETH = $12 💳addres Of supply: 0x0b4a7e3e7DBa45509F1948eD388d521f862270B1

**Comment by ultperf** [comment]
@q9f, can u gimme one more 100 goerlis? please? 
on either address below?
0xF47DdD15d21dD39E2fFBA671913573a0eD7A1cC4
0x9604Cf64a20c67304488C08db277D7963dCFD0BF

will help you back in future for code contribution, testing time or NFT for US$100.
truly needed. appreciate this. thx in advance!
