### ISSUE TITLE
I kindly ask the community to give me 10000 eth goerli to test my project.

### ISSUE THREAD

**Issue by MasterMe4a** [eth-clients/goerli#153]
I kindly ask the community to give me 10000 eth goerli to test my project. I would be very grateful if you send me to the address: 0x6A25F34952365AFbcCd2c92015fA33B36CFc800D

**Comment by q9f** [comment]
Please use Sepolia.

**Comment by Anonimscrypt** [comment]
Hello everyone, if you have trouble finding goerli testnet you can contact me to buy Telegram: https://t.me/SnowdenResearch Im Selling $Goerli $ETH ! 💰20 Goerli ETH = $5 💰50 Goerli ETH = $12 💳addres Of supply: 0x0b4a7e3e7DBa45509F1948eD388d521f862270B1

**Comment by Anonimscrypt** [comment]
Hi everyone if you have trouble finding goerli testnet And need some tesnet goerli eth you can contact me to buy
Telegram: 
https://t.me/SnowdenResearch
Im selling GoerliETH
📌Price:
20 Goerli ETH for $5
40 Goerli ETH for $10
50 Goerli ETH for $12
💳Proof of Supply:
https://goerli.etherscan.io/address/0x0b4a7e3e7DBa45509F1948eD388d521f862270B1
