### ISSUE TITLE
Firewall block

### ISSUE THREAD

**Issue by BetDEXben** [eth-clients/goerli#155]
We are developing a project, We by the national firewall block, we can't get test token through the FAUCET

We need 2000 goerli test token for distributing to the community of users

please:0xa7Ce9f93308fDE2F8C6c3e1C6fd22dc282AFB4C0

**Comment by Anonimscrypt** [comment]
Hi bro if you have trouble finding goerli testnet And need some tesnet goerli eth you can contact me to buy
Telegram: https://t.me/SnowdenResearch
Im selling GoerliETH
📌Price:
20 gETH = $5
40 gETH = $9
💳adress of Supply:
https://goerli.etherscan.io/address/0x0b4a7e3e7DBa45509F1948eD388d521f862270B1

**Comment by BetDEXben** [comment]
what you mean? does goerli really require everyone to buy it? isn't that just a test coin

**Comment by Anonimscrypt** [comment]
The fact that  gETH has value
All faucet are dry.  all dev have to buy Testnet Eth
