### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Harpam123** [eth-clients/goerli#162]
Can i request 1000 goerli token for add liquidity my token on uniswap

**Comment by kavitrmehta** [comment]
When I paste the tweet link at [https://goerli-faucet.mudit.blog](https://t.co/UNCefsJKO3) and select one of the three dropdown options, I get this issue - insufficient funds for gas * price + value. How do I solve this? Or can someone help me get 10 to 20 Goerli tokens?

**Comment by zenwraight** [comment]
When I paste the tweet link at [https://goerli-faucet.mudit.blog](https://t.co/UNCefsJKO3) and select one of the three dropdown options, I get this issue - insufficient funds for gas * price + value. How do I solve this?

**Comment by pk910** [comment]
Goerli is deprecated and running out of funds.
Try one of the faucets from https://faucetlink.to/goerli
Unfortunately there is no way to get higher amounts of GoETH freely anymore.

You should head over to the Sepolia testnet.
The network is the currently supported testnet for dApp development and it is a lot easier to get some funds there.
