### ISSUE TITLE
Kindly send free ether

### ISSUE THREAD

**Issue by shaghil65** [eth-clients/goerli#164]
Hi, I need 320 Goerli ETH to test validator creation and funding.
0x47574F2a8e75cd7942763F1caFF9FAf2473fcC0c

**Comment by wissam0alqaisy** [comment]
0x8d94113AB6cee3E9bCC72dc12bA4FA85BED9243B
Thanks

**Comment by Alireza5658** [comment]
0xa34a09e169e0662b2DeF882E0D102ef466cb943A
    Tanks

**Comment by liuliang** [comment]
0xbb51B683845c7390Fcef56357ca0C10d0E7eD700
Thanks I need 16 validators
