### ISSUE TITLE
Want 64gETH for 2 validators

### ISSUE THREAD

**Issue by TinyVege** [eth-clients/goerli#171]
My address is 0x144aACF5CB30aa4FbF00F4A1b5bce22E1E9602f3
thank u very much

**Comment by reza0982** [comment]
I need 64 GoETH for run 2 validators
0x6f34942b918647b0a08ebb7efff2ab9a8507de6d

**Comment by ThirawatChuaiklang** [comment]
0x98BE61F7052Dfbbc10E5e6280730C024cF187c4E
