### ISSUE TITLE
GoerliETH

### ISSUE THREAD

**Issue by kornijchuk** [eth-clients/goerli#183]
What can i do with GoerliETH?There are a little of it on my wallet.What should i do with it or there is nothing i can do? 

![image](https://github.com/eth-clients/goerli/assets/156716048/f7be3b92-d7b2-491b-8076-e4db744c41e9)

**Comment by dmBlun** [comment]
ok

**Comment by Brkoslav04** [comment]
Ok

**Comment by Brkoslav04** [comment]
> Co mohu dělat s GoerliETH? Trochu toho mám na peněžence. Co s tím mám dělat, nebo nemůžu nic dělat?
> 
> ![obraz](https://private-user-images.githubusercontent.com/156716048/296875663-f7be3b92-d7b2-491b-8076-e4db744c41e9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTYwNDYsIm5iZiI6MTcwNzYxNTc0NiwicGF0aCI6Ii8xNTY3MTYwNDgvMjk2ODc1NjYzLWY3YmUzYjkyLWQ3YjItNDkxYi04MDc2LWU0ZGI3NDRjNDFlOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMDE0MjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjBiNGZiMmFmZDIyNDM1MjljZTJhMjJkZjk2MTkwMTZiYjIwZjMxZWZjOTZiNmNmYjk2YjYwNjM1YjA2NTZkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vaTNRgfG95tXu6b_kYw7sMxbFvzIwYoaCO6UyOZ3ivc)

**Comment by Phuchong0259** [comment]
ผมเองนี้แหละคะบ

**Comment by Figures7** [comment]
How is this to not on my wallet

**Comment by reza0982** [comment]
goerli is only used to test testnet projects, validators or whatever, it has no value in the market,

**Comment by Luqman2511** [comment]
???
