### ISSUE TITLE
Looking for peers

### ISSUE THREAD

**Issue by isifidio** [eth-clients/goerli#79]
Goerli starts the --fast mode, and cannot find other nodes after synchronizing to the last few blocks. Why?

Do I need to turn on the full mode?

**Comment by roninkaizen** [comment]
hello, 
could you provide little more details about runtime environment
and connectivity please?

**Comment by Jiangzy520** [comment]
> 你好， 您能否提供有关运行时环境的更多详细信息 和连接好吗？



> 你好， 您能否提供有关运行时环境的更多详细信息 和连接好吗？ roninkaizSir, can you give me some goerli for homework? This is my address 0x5336288884ec81a73fd7bcf7fb36ede45ec3e44d. Thank youen,
,

**Comment by q9f** [comment]
I'm running two bootnodes:

```
enode://d4f764a48ec2a8ecf883735776fdefe0a3949eb0ca476bd7bc8d0954a9defe8fea15ae5da7d40b5d2d59ce9524a99daedadf6da6283fca492cc80b53689fb3b3@nunki.htznr.fault.dev:32109
enode://d2b720352e8216c9efc470091aa91ddafc53e222b32780f505c817ceef69e01d5b0b0797b69db254c586f493872352f5a022b4d8479a00fc92ec55f9ad46a27e@acrux.htznr.fault.dev:30303
```

**Comment by TinyVege** [comment]
> 

thanks

**Comment by TinyVege** [comment]
> Just keep it running, it will find peers after some time. The next release will have the updated bootnodes.

thanks

**Comment by dpulife** [comment]
Hi there, please give me 32 ETH, thank you!
0x194Bef0264F65946F60AEbdC6aaA9b47e68E82De
