### ISSUE TITLE
I'm sorry to contact you this way

### ISSUE THREAD

**Issue by ghost** [eth-clients/goerli#94]
We are launching a project now, but there is so much money on the market from taps that too many people are getting into our test network
, so we want to obtain/purchase some Goerli ETH and distribute Goeri ETH by our exclusive address, but we have no channel to contact you. This is the only lame way to get in touch with you.
We are about to get 10W Goerli ETH. If not, we can buy it, but we hope the price will not be too expensive. We are a grassroots team.

Email address: wozxd2019@outlook.com
Address: 0 x034b4cd6c8a23c268f91d059993c6e74d9626ef4

**Comment by q9f** [comment]
Don't worry. The price is $5.

**Comment by Jiangzy520** [comment]
> 不用担心。 价格是 5 美元。
Sir, leave your BSC address or eth address. My team is also working for VVS, ZKT, eth2 This is my wallet address 0x5336288884ec81a73fd7bcf7fb36ede45ec3e44d zhongtiankeji88@qq.com This is my email. I hope you can contact me,

**Comment by Jiangzy520** [comment]
> 不用担心。 价格是 5 美元。

Because the project started on April 12, I hope you can understand that I am so eager to find you
