### ISSUE TITLE
Coordination-Thread: Merge Göerli execution-testnet with Prater consensus-testnet

### ISSUE THREAD

**Issue by q9f** [eth-clients/goerli#98]
This is an early notice to the Göerli validators that the intention is to merge(TM) the Goerli execution-testnet with the Prater consensus-testnet. In case of a merge, Clique-POA validators will be relieved from their duty and replaced by the Beacon-POS validator set of the Prater network.

Tagging current validators @q9f @roninkaizen @igorbarinov @jparyani @prestonvanloon @tkstanczak @egalano @Errorific @karalabe - if you want to continue validating after the merge, make sure you have a Prater validator.

* Prater: [eth-clients/eth2-networks/shared/prater](https://github.com/eth-clients/eth2-networks/tree/master/shared/prater)
* Deposit Contract: [0xff50ed3d0ec03aC01D4C79aAd74928BFF48a7b2b](https://goerli.etherscan.io/address/0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b#code) (Göerli -> Prater)

cc @parithosh

**Comment by prestonvanloon** [comment]
Thanks @q9f!

As I understand it, Goerli sealers will continue to perform their work until the _terminal total difficulty_ is reached and then these sealers can be safely turned down/off. 

How will we coordinate a difficulty change in Goerli clique?

**Comment by q9f** [comment]
I don't think there should be much of a difference, we just have to select a sensible terminal total difficulty. Each block in clique adds 1 or 2 difficulty.

**Comment by Jiangzy520** [comment]
> 我认为应该没有太大区别，我们只需要选择一个合理的终端总难度。 clique 中的每个块都会增加 1 或 2 个难度。

Afr Schoe I can get some goerli in you and do a 2.0 test. This is my wallet address 0x5336288884ec81a73fd7bcf7fb36ede45ec3e44d. Thank you

**Comment by yangdiweif** [comment]
@q9f @roninkaizen Some validators have sold hundreds of thousands goeth from these validators address. They didn't use it for validator, they are selling it. That's awful.

**Comment by q9f** [comment]
nobody is selling goerli ether, it has no value. it's a testnet. if someone sells you goerli ether, they are a scammer.

**Comment by q9f** [comment]
Updated the website https://goerli.net/ 🤓

**Comment by q9f** [comment]
I activated 20k validators on Prater on behalf of Goerli.

https://prater.beaconcha.in/blocks?q=Goerli

**Comment by q9f** [comment]
created a web app for block numbers and difficulties

![Screenshot at 2022-06-03 13-58-44](https://user-images.githubusercontent.com/58883403/171849390-74736d2f-143f-4d77-a252-be7639c6c027.png)

**Comment by ryanschneider** [comment]
@q9f will we need to update our current Clique validator to run alongside a CL pair or will configuring them w/ a new EL that accepts the TTD be enough?

**Comment by q9f** [comment]
> @q9f will we need to update our current Clique validator to run alongside a CL pair or will configuring them w/ a new EL that accepts the TTD be enough?

I have my EL authority on a different machine than the CL validators, but it should be perfectly fine to have both on the same machine.

**Comment by timbeiko** [comment]
Goerli has now merged 🎉 ! Should we close this?

**Comment by q9f** [comment]
🎉

**Comment by ryanschneider** [comment]
Sorry i should’ve been more clear. I maintain the Infura clique signer.
What updates, if any, are required for the existing clique signers to make
sure the chain completes the merge?  For example do we need to enable the
engine API on our signer and pair it with a CL, or update the EL to a new
version that accepts a TTD, or simply do nothing and shut down the clique
signer once the merge completes?

**Comment by parithosh** [comment]
Now that Goerli has been merged, there's no reason to run the clique signers anymore. They can be shutdown.
